"""Adiciona campo imagem ao Produto

Revision ID: 2fe1e778e595
Revises: f5a352c2b599
Create Date: 2025-04-22 21:50:00.635503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fe1e778e595'
down_revision = 'f5a352c2b599'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagem', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.drop_column('imagem')

    # ### end Alembic commands ###
