"""Adiciona tabela ProdutoInsumo

Revision ID: 4e8de1127d2c
Revises: 659bbf8596cf
Create Date: 2025-04-25 18:52:11.537204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e8de1127d2c'
down_revision = '659bbf8596cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produto_insumo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('insumo_id', sa.Integer(), nullable=False),
    sa.Column('quantidade_necessaria', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['insumo_id'], ['insumo.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('produto_insumo')
    # ### end Alembic commands ###
