"""adiciona campo estoque ao insumo

Revision ID: 714148255ee6
Revises: 2fe1e778e595
Create Date: 2025-04-25 15:51:42.685146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '714148255ee6'
down_revision = '2fe1e778e595'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.alter_column('imagem',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.alter_column('imagem',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)

    # ### end Alembic commands ###
